### PR TITLE
Change UI.

### PR DESCRIPTION
**Pull request by JackDandy**
Update jquery confirm 1.x to 2.7.0.
Update fancybox 2.1.5 to 2.1.6 (c00852a).
Add jquery-throttle-debounce 1.1 to regulate methods called in rapid succession.
Add mousetrap 1.6.0 keyboard shortcut handler.
Change reorder displayshow submenu items and remove button display lag.
Change add Pause/Unpause and Hide/Unhide Specials to displayshow submenu.
Change highlight menu item of current viewed page.
Change darken the lighter panels of the dark theme.
Change color on hover of 'Edit' and 'Remove' buttons on displayshow submenu.
Change color on hover of 'Logout', 'Restart' and 'Shutdown' menu items.
Change displayshow, rename key item "Low Quality" to "Upgradable" and hide when not in use.
Change displayshow, explicitly display counts of episodes and specials in description.
Change reword text of remove show dialog.
Change color headings of 'Logout', 'Restart', 'Shutdown' and show 'Remove' confirmation dialogs.
Change add confirmation dialog to 'Clear errors' button on 'View Errors' page.
Change refactor CSS to improve browser processing time (removed ~20% redundancy).
Change vastly simplify config pages with a button to display More/Less Gear
Change only show More/Less Gear button when more options are available.
Change use a distinguishable text label color to highlight exposed options.
Change Show List page, move existing tag groups into tabs and number of visible shows.
Change Show List, simplify page with new layout, sort and search controls.
Add fanart to Show List.
Change move menu item config/"About" to "Tools" menu.
Add key shortcuts and list them on the "About" page.
Add Esc key on Show List focuses the search box so can disable config/general/interface/"Give show list search focus" in order to use other key sequences easier by no longer requiring an initial Esc to defocus the search box.
Fix (forever) bug, remove never used fileBrowser ctor that was raising browser errors.
Change add a short delay to the menu hover-over to prevent a false positive display.
Change add a short delay to the menu move-away to prevent a false positive hide.
Add filter helper button to toggle filter between contains, starts, and ends with) on Show List.
Change Show List, filter accepts JS regular expressions (e.g. ^e and e$ filters shows that start, end 'e' respectively).
Add lamp under config menu to override default light or dark theme on a per browser basis.
Fix validate edit show and db stored value for scene exception season.

### CODE REVIEW

**Comment by JackDandy** [comment]
@jetskijoe

Hiya, I put this question here as it will be easy to delete afterwards :)

Is there something on your clone that would be better merged into head so that you can simply update directly from the repo and save time ?

**Comment by jetskijoe** [comment]
I made 2 changes in my branch that I like but it is probably not a good
merge for you.
1) is I allow DVDRIP to override HDTV and 720web-rip I also.  I like to
have the smaller sizes for archive.
2) I updated the post-process to allow smaller files for the size.

**Comment by JackDandy** [comment]
@jetskijoe ah yeah, you're right, change 1 could create logic issues in other places, k np.

**Comment by JackDandy** [comment]
@jetskijoe ah yeah, I think you *may* be right, change 1 could create logic issues in other places, but I will ask.

**Comment by JackDandy** [comment]
Yeah, the way you have hardcoded a quality to use the number of another is really suitable only for you, that would break many things for everyone. Shame. Ah well.

**Comment by deed02392** [comment]
Wow. Great work

**Pull request closed without merging**
