### PR TITLE
Add BeyondHD provider

### PR DESCRIPTION
**Pull request by adam111316**
TODO
- [ ] Make @alazare619 test everything

### CODE REVIEW

**Comment by alazare619** [comment]
To funny will do

**Comment by adam111316** [comment]
updated

**Comment by JackDandy** [comment]
- [ ] verify propers, airbydate shows function as expected

**Comment by adam111316** [comment]
@alazare619: I'd like to get this provider in, could you confirm the above tests JD mentioned above?

**Comment by alazare619** [comment]
Propers haven't had any come across or air by date all others work great

**Comment by adam111316** [comment]
Can you simulate it. eg download a file that you know has been propered. Then run a propers search and see if its picked up. Also try adding a show with airbydate and check its okay. @JackDandy will yell at me if I merge code that doesn't work :P

**Comment by alazare619** [comment]
as far as propers go i was able to test, air by date i havent even found anything that is air by date on site so unable to test (i suppose i could make the bot pull a air by date show onto the site) but i dont forsee bhd even going that route as far as shows they auto up.

**Comment by JackDandy** [comment]
Actually, releases type "propers" are *not* picked up.
Also, show name exceptions are *not* cycled through.

I addressed the above and other issues in another PR so will close this one.

**Pull request closed without merging**
