### PR TITLE
Change HTTP auth to a login page

### PR DESCRIPTION
**Pull request by adam111316**
Change to improve webserve code
Add logout menu item with confirmation
Add 404 error page

### CODE REVIEW

**Comment by JackDandy** [comment]
Bug: Setup 2 tabs. In  tab 1... logout. Refresh tab 2. The url has the next= query param.  After credentials are entered, next= fails to be redirected and home displays instead.

**Comment by adam111316** [comment]
@JackDandy incorporated your fixes, and issue 2) is fixed

**Comment by adam111316** [comment]
Issue 1) fixed.

**Comment by adam111316** [comment]
@JackDandy 1), 2) and 3) are all fixed

**Comment by adam111316** [comment]
updated / rebased

**Comment by JackDandy** [comment]
1) confirmed fixed

**Comment by adam111316** [comment]
3) Fixed
1-new) Fixed

**Comment by JackDandy** [comment]
3) Confirmed

**Comment by JackDandy** [comment]
1) When logged out, do GET /ui/get_mesages
404 page displays *but* so does all the menus that should no longer display and also the javascript files are loaded too, e.g. fuzzy time (see network traces)

**Comment by adam111316** [comment]
Fixed 1) & 2)

**Comment by JackDandy** [comment]
yup, both verified fixed.

**Comment by JackDandy** [comment]
1) tab #1, go to /api/builder
2) tab #2, go e.g. /home
3) tab #2 /logout
4) tab #1, browser refresh, the login screen is displayed with "next=api/builder"
5) tab #2 do the login creds, get taken to home or wherever
6) tab 1, just hit refresh (dont enter login details as they were already done in #5) - OOPS taken to home, should be taken to next=api/builder
5) tab

**Comment by adam111316** [comment]
Fixed

**Comment by JackDandy** [comment]
quotes missed in confirmations.js

**Comment by adam111316** [comment]
Fixed

**Comment by JackDandy** [comment]
Change text on config/general from "HTTP username" -> "Username" and "HTTP password" to "Password", rebase first to pull in changes set up as a prelude to this change.

**Comment by adam111316** [comment]
1,2,3,4 fixed

**Comment by CtrlAltDefeat94** [comment]
When trying to login with a wrong user/pass, there is no error message to tell what's wrong. You are only redirected back to the login page.
Is that a bug or by design?

**Comment by adam111316** [comment]
@CtrlAltDefeat94: I've changed that feature to a new feature that includes an error message.

@JackDandy  or @Supremicus might be needed to style the text however

**Comment by JackDandy** [comment]
dark.csss#355

.submenu-icon-plex {
	background-position: -462px 0;
}

change to...

.submenu-icon-plex {
	background-position: -462px -3px;
	margin-top: 3px;
	height: 10px;
	position: relative;
}

edit the same submenu-icon-plex class in light.css

**Comment by adam111316** [comment]
@JackDandy done

**Comment by JackDandy** [comment]
Can you remove auth requirement from /fonts so that if a /fonts/* request is made, that there is *NO* redirection or next= query params added to files coming from that route

**Pull request merged**
