### PR TITLE
Fix "too many redirects" or "no CSS/JS content" delivered.

### PR DESCRIPTION
**Pull request by JackDandy**
Init # Main Handler last for Tornado.

### CODE REVIEW

**Comment by qorron** [comment]
I still have the issue with 45c9ca7884f35a0cb3659a465ace59210bd42b22 while trying to login and the nzbToMedia script gets that as well. (switched to master for now)

**Comment by JackDandy** [comment]
Did your file on develop actually update... it should like this after the update (note the line numbers)
https://github.com/SickGear/SickGear/blob/develop/sickbeard/webserveInit.py#L99-L124

**Comment by qorron** [comment]
git said it was on 45c9ca7884f35a0cb3659a465ace59210bd42b22 with no local changes but I can retest this if there is doubt.

just rechecked it: yep, still broken

**Comment by JackDandy** [comment]
I guess you best stay on master unless we somehow reproduce what you see, this has been confirmed to work fine on four systems so far, that said, there has been reported issues when updating.

**Comment by JackDandy** [comment]
@qorron i think i found the issue...
stop sg... from all <install_dir> subdirs...
delete *.pyc
delete *.pyo
then start up devel

**Comment by qorron** [comment]
thanks, that fixed it!

**Comment by JackDandy** [comment]
excellent, thanks

**Pull request merged**
