### PR TITLE
rtorrent: use relative rpc imports

### PR DESCRIPTION
**Pull request by makefu**
This PR changes the `import rpc` calls in lib/rtorrent to relative calls. It is required to run SickGear with `python3`

### CODE REVIEW

**Comment by JackDandy** [comment]
Thank you for this PR, additional issues in relation to rT + py3 have been found and a hotfix branch can be created. Are you able to test it works for you ?

**Comment by makefu** [comment]
@JackDandy i am currently running the 0.21.6 plus this patchset with python3 interpreter.
I somehow got side-tracked by an issue with the HorribleSubs search plugin and landed here :)

I can, however only test stuff related to torrents (with rtorrent) and animes.

**Comment by JackDandy** [comment]
> test stuff related to torrents (with rtorrent)

okay. i'll get back to you here when ready

**Comment by JackDandy** [comment]
Ok to test...

**Comment by makefu** [comment]
with your hotfix branch i get:

image

**Comment by makefu** [comment]
Trying to update a show:
image
This seems to be related to setting an alternative name for a show

**Comment by JackDandy** [comment]
Fixed pushed.

Note; you _may_ need to checkout to master, then back to the hotfix to pull the changes.

**Comment by JackDandy** [comment]
good?

**Comment by makefu** [comment]
with the new branch commit i see the following error in the error-log:
image

in /config/providers i get a new error:
image

updating a show is now working correctly

**Comment by JackDandy** [comment]
Ok, now that import fix is confirmed good, i used it in all other places, you should be good now

**Comment by JackDandy** [comment]
good ?

**Comment by makefu** [comment]
@JackDandy looking good as of now. i will continue using it.

btw for the py3 fork  i also apply the following patch:
```patch
diff --git a/SickBeard.py b/SickBeard.py
index 31cfd1e1..10a4ef5e 100755
--- a/SickBeard.py
+++ b/SickBeard.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python3
 #
 # This file is part of SickGear.
 #

```

**Comment by JackDandy** [comment]
Thanks, the problem with your suggested change is that is could break py2 usage, see the [roadmap](https://github.com/SickGear/SickGear/wiki/FAQ-Roadmap) for Python support.

**Comment by JackDandy** [comment]
> looking good

Thanks. :)

> for the py3 fork

To correct, it's not a py3 **_fork_**. Python3 support was added to core. Therefore, the issue with your suggested change is that it _could_ break SG for py2 users, see the [roadmap](https://github.com/SickGear/SickGear/wiki/FAQ-Roadmap) for Python support.

**Comment by makefu** [comment]
@JackDandy that is true, maybe leave it at `python` and let every distro figure out what they think the best python is for them.

Regarding `py3 fork` i meant my local fork :+1:

**Comment by JackDandy** [comment]
What would be interesting to know for sure is **IF** it is changed from `python2` to `python` how or if distros really make a decision to which Python binary to execute. However, currently, knowing that py2 is working fine, it is a worry that changing it to even `python` could result in some installations breaking. As it's unknown what such a change would do - I am very wary.

**Comment by makefu** [comment]
@JackDandy that is a fair point, better be safe than sorry :)

**Comment by JackDandy** [comment]
I will add something in the wiki about this as i am sure you will not be that last to ask this same thing 😉

**Comment by JackDandy** [comment]
Thanks for your help with this PR.

The issues covered are fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.7)

**Pull request closed without merging**
