### PR TITLE
Remove IMDb library

### PR DESCRIPTION
**Pull request by adam111316**
Remove star rating and country flag from display show page

We lose out on ratings and flags, however the IMDb api is slow and greatly slows down the show updating process. I don't think it's worth keeping around this bloated lib.

### CODE REVIEW

**Comment by adam111316** [comment]
WARNING: Includes a DB version bump

**Comment by JackDandy** [comment]
I was looking at this too due to the huge impact it has on SHOW-UPDATE process. However, I wasn't so sure about removing it entirely as it *does* pull in 2char country codes which may well be used by subtitles, also i don't know if there may be something else of any real use as i only briefly looked.

So as an idea, **move** the IMDB lookup process from being run in the SHOW-UPDATE process flow to instead occur for a given show just before that show is snatched and after the best quality is know for what is about to be snatched.

**Comment by adam111316** [comment]
Subtitles are dependent on the users selected language, rather than the language the show is in iirc.

**Comment by JackDandy** [comment]
ah ok, still, i'd rather not lose data from IMDB, instead it would be nice to have even more in terms of the actor stuff, but the timing of when to action the process flow is key :)

**Comment by adam111316** [comment]
Still seems like bloat to me. The libs don't even parse or save the actors at the moment (even if they did I don't really see the point). There is no need to add additional complexity to the code just to try and keep a rather useless library that adds little to no gain.

**Comment by adam111316** [comment]
As @JackDandy has plans for using this lib, closing this PR.

**Pull request closed without merging**
