### PR TITLE
Change to consolidate scene exceptions and name cache code

### PR DESCRIPTION
**Pull request by adam111316**

### CODE REVIEW

**Comment by CtrlAltDefeat94** [comment]
I tried to PP all Minami-ke episodes, but the Minami-ke Tadaima(season 4) episodes got PPed as season 1
https://gist.github.com/CtrlAltDefeat94/5ee96d51f583d53e86fb (Bottom to top)

Fairy Tail (2014) (Season 2 by japanese numbering, Season 5+ by american) episodes are not recognised at all.
https://gist.github.com/CtrlAltDefeat94/2f0ebf65f407ce230412 (Top to bottom)

**Comment by adam111316** [comment]
@CtrlAltDefeat94 Fixed Minami-ke (was bad data on xem)

**Comment by JackDandy** [comment]
```
https://github.com/SickGear/SickGear/pull/374/files#diff-20ae3ea66e1e609945cdfbb4419e5a3dL343
```
Some systems show better performance by having this. Puzzling that it hasn't (before this pr) changed from the hard-wired 0.2 value to the regulation setting in user config settings, a better way for those folks that do need that tuning capability than removal?

**Comment by adam111316** [comment]
@JackDandy: I suppose so

**Comment by adam111316** [comment]
Changed sleep timer and rebased

**Pull request merged**
