### PR TITLE
Change to allow file moving across partition.

### PR DESCRIPTION
**Pull request by JackDandy**

### CODE REVIEW

**Comment by adam111316** [comment]
What needs to be tested here?

**Comment by JackDandy** [comment]
[ ] pp move from one partition to a destination on another partition
[ ] pp move and symlink file from one partition to a destination on another partition
[ ] pp rename ep file

**Comment by adam111316** [comment]
Ah bugger, I don't have non-win machines with multiple partitions

**Comment by adam111316** [comment]
That said I suppose /tmp is a separate partition

**Comment by adam111316** [comment]
All good :+1:

**Pull request merged**
