### PR TITLE
Update network logos to their current logo

### PR DESCRIPTION
**Pull request by Supremicus**
Add Chiller and ABC news 24 network logos
Remove redundant adult swim logos

### CODE REVIEW

**Comment by Supremicus** [comment]
Yeah completely forgot about the outlines, fixed.

**Comment by JackDandy** [comment]
Thanks

**Comment by Supremicus** [comment]
reverted those few, should be good.

**Comment by JackDandy** [comment]
Thanks

**Comment by JackDandy** [comment]
Logos: Oxygen, TNT, Tru TV, TV Land, TVNZ, WE TV, Xbox, YouTube
Again Thanks

[edit] added ABC News

**Comment by Supremicus** [comment]
done

**Comment by JackDandy** [comment]
I figured tvnz would be to small to reach that sweet spot. The others look great, a solid improvement all over. Thank you :+1:

**Pull request closed without merging**
