### PR TITLE
Add Rarbg provider

### PR DESCRIPTION
**Pull request by JackDandy**
Add Rarbg API v2 provider.

Note: The merging of all qualities into one category in API v2 mean more results likely to be cropped. The vendor switched to this method from their (imho, better) original of listing category numbers. It was suggested that clients add and maintain all possible search strings that signify as quality. However, this would still trigger misses, introduce other issues, plus add needless non-standard API complexity. **Conclusion;** as designed, SG will utilise other configured providers when this one fails to hit targets, *this provider should not be configured as a sole provider*.

### CODE REVIEW

**Comment by rarbg** [comment]
Your code should actually use the API docs here https://rarbg.com/pubapi/apidocs.txt

**Comment by JackDandy** [comment]
@rarbg thanks for the feedback, i am now implementing your API, but i have found an issue. When using search_tvrage, search_tvdb to avoid the use of search strings (and reduce the server load) then i can specific season AND/OR episode. Can you implement?

**Comment by rarbg** [comment]
@JackDandy 
You can use both the search and search_tvrage/search_tvdb/search_imdb at the same time :)
?mode=search&search_imdb=tt123456&search_string=Test%20Search&token=xxxx

**Comment by JackDandy** [comment]
@rarbg thanks for getting back so quickly:)

I tried using both params but the issue I found was that if I use the *very fast* integer id param (e.g. search_tvrage=1234), then I cannot specify for example search_string=s01e02 (I get zero results).
I am forced to send "search_string=Showname s01e02" which is counter to reason of using the ID that guarantees the results always belong to the searched on ShowName.
It would be far better that the two were used in concert, so that i can send either...
a) tvrage_id and search_string=s01 .. resulting in 100 items of say 24 episode releases of season 1
b) tvrage_id and search_string=s01e02 .. resulting in a number of episode 2 releases items of season 1

**Comment by rarbg** [comment]
@JackDandy 
Can you please send me the api request you are doing so i can tell you why its happening asap ?
I can think of 2 reasons why it can be happening
1. ranked param
2. the show you are trying to find has no tvrage in our db  , it happens sometimes

**Comment by JackDandy** [comment]
@rarbg

Sure...
* mode=search&search_tvdb=268872&category=18;41&limit=100&sort=last&token=12345
* mode=search&search_tvdb=268872&category=18;41&limit=100&sort=last&search_string=s02e12&token=12345

**Comment by rarbg** [comment]
@JackDandy 
Working on it. Give me 10

**Comment by JackDandy** [comment]
@rarbg awesome thank you very much :+1:

**Comment by rarbg** [comment]
@JackDandy 
Done ;)

**Comment by JackDandy** [comment]
@rarbg so much better, thank you :+1: :+1:

**Comment by rarbg** [comment]
@JackDandy 
np :)

**Comment by JackDandy** [comment]
@rarbg 
oh sorry, one last thing, I can do...
a) search_string=s02e12
but not...
b) search_string=s02

**Comment by rarbg** [comment]
@JackDandy 
Done :) Fixed

**Comment by JackDandy** [comment]
@rarbg most excellent :)

**Comment by JackDandy** [comment]
@rarbg 

Testing found two further issues..

a strange response text...
for params with ... &search_tvrage=7074&search_string=
response = "Cant find search_tvrage in database. Are you sure this imdb exists?"
but imdb param isn't being used, so I removed the "search_string=" and all was ok.

Also, search_tvrage=7074 = "8 out of 10 Cats" - the web ui returns results, but the api doesnt even with ranked=0 and no limiters like seeds or leechers.

**Comment by rarbg** [comment]
@JackDandy 
Thats because we dont have imdb <-> tvrage on this show + as you can see from our web ui the show doesnt have imdb on. Meaning even if we had the relation for this particular show the results wont be returned

**Comment by JackDandy** [comment]
@rarbg 

1) erm, well i think result (1) is incorrect, and my rationale to this is when you reproduce the step and remove the param string as indicated, the output does not mention imdb anymore.
2) results 2, did you manage to repro this one

**Comment by rarbg** [comment]
@JackDandy 
Give me result 1 + 2 api calls because i really cant understand what you are trying to do

**Comment by JackDandy** [comment]
@rarbg 
(a) mode=search&token=12345&category=18;41&limit=100&sort=last&search_tvrage=7074&search_string=
(b) mode=search&token=12345&category=18;41&limit=100&sort=last&search_tvrage=7074

Issue 1) Repro's strange output by simply omitting "**search_string=**"
Issue 2) Call (b) gives zero results yet the show  "8 out of 10 Cats" has webui results

**Comment by rarbg** [comment]
@JackDandy
Thats because we dont have imdb <-> tvrage on this show + as you can see from our web ui the show doesnt have imdb on. Meaning even if we had the relation for this particular show the results wont be returned.
(a) output is normal and expected, because it cant find the imdb for tvrage 7074
(b) you can see in the webui that the show doesnt have imdb , meaning there cant be a tvrage relation in our db or any other relation in our db

**Comment by JackDandy** [comment]
@rarbg 
So is all your records forced linked to imdb because we don't use imdb IDs or make requests with them, it is strange that imdb is even brought into the conversation.

**Comment by rarbg** [comment]
@JackDandy 
Im sorry but i think its better not to integrate us.

**Comment by JackDandy** [comment]
Huh? What is wrong? Ok, there must be a misunderstanding. No problem. I was trying to help. I will no longer bother you, and i'm sorry that I somehow offended you. The was 100% not my intention.

**Comment by rarbg** [comment]
@JackDandy
You didnt offend me. For the sake of it ill try to explain what i already explained 2 times in a different way... Api works like that :
You make a call with tvrage/tvdb/whatever -> its looks up in a table ( lets call this table table_x ) which keeps imdb tt to tvrage/tvdb/whatever. The torrents you see on the "web" or via the api keep only imdb tt in another table.
When you make the call it returns you that it cant find the imdb of the show because :
1. we dont have  tvrage<->imdb tt in table_x 
2. even in the "web" you can see there is no imdb assigned to those torrents. meaning even if you decided to search by imdb it wont return them. thats why ranked=1 is the default , because its released by rartv ( our official tv group ). ettv & etzv are ranked 0 because its not guaranteed to have imdb/tvrage/whatever + they usually have problems with their bots.

**Comment by JackDandy** [comment]
@rarbg

* `https://rarbg.to/torrents.php?search=Jimmy+Fallon+2015.05.21`  
**success results found.**
* `pubapi.php?mode=search&category=18;41&ranked=0&sort=last&token=xxxx&search_string=Jimmy Fallon 2015 05 21`  
**success results found.**

* `https://rarbg.to/torrents.php?search=Jimmy+Fallon+2015.04.27`  
**success results found.**
* `pubapi.php?mode=search&category=18;41&ranked=0&sort=last&token=xxxx&search_string=Jimmy Fallon 2015 04 27`  
**fail no results.**

**Comment by rarbg** [comment]
@JackDandy 
Simple - There is no 2015.04.27 uploaded from external groups , unranked

**Comment by rarbg** [comment]
Wait. Sorry. I didnt read it right , give me a sec to check

**Comment by rarbg** [comment]
@JackDandy 
The api searches only in the last 10000 torrents except for imdb,tvrage,tvdb.
Jimmy Fallon 2015 04 27 is not within the last 10000 torrents

**Comment by JackDandy** [comment]
okay

**Comment by JackDandy** [comment]
@rarbg

is there a way to do an OR operator in the search_string?

for example, we use "PROPER|REPACK|REAL" in the one API call to return releases that can contain any combination of the above

**Comment by rarbg** [comment]
@JackDandy 
There is no way to OR but are you making 2 different api calls ? one with PROPER|REPACK|whatever and one without to see if there is proper|repack|whatever ?

**Comment by JackDandy** [comment]
@rarbg 
Yeah I kinda guesed that would be the case, so I started making it process how the original sickbeard does for indexers. That is making two calls, one with "whatever PROPER", and "whatever REPACK".

**Comment by rarbg** [comment]
@JackDandy 
https://github.com/rarbg/torrentapi/issues/1
Im coding v2 of the api , are you ok for the OR to be [something|something2] ?

**Comment by JackDandy** [comment]
You may have an issue using single square brackets because *release group names* use them, especially anime releases. So i;'m not sure how that will affect. Other providers simply use ..
`something|something2`

**Comment by rarbg** [comment]
@JackDandy 
Do you always put _SPACE_ before and after the PROPER|REPACK|REAL ? Because if you do its ok for me to do it in v2 instead of []
About timezone - sure ill make it return in UTC

**Comment by JackDandy** [comment]
@rarbg 

To answer your question first, yes I have been using space at the moment to produce results.

The issue with using space, is that it is **not** a widely used standard. At least the period "." is standardised in line with scene rules. Rules give order and anchor points that can reliably coded for, which in turns makes search and other systems faster, reliable and generally more efficient. Worse, however, a space can produce a false positive because the word can be contained in either a show name or an episode name, whereas `.PROPER.` or `.REPACK.` is less likely due to the dot that is used as a definitive word boundary. Maybe your db doesn't have dots though, so that means you are stuck. However, I have seen with anime what happens when websites make their own rules (at all becomes chaos) and no one links up like the scene (imho) smartly did.

**Comment by rarbg** [comment]
@JackDandy 
You dont understand me at all lol! Its not about the dots , everything in our db is with dots anyways :) Its not about how the search works. Ill make it work exactly as it should work
Just tell me how do you want to make the query ?
To make it fast performance wise and know that the query you are doing is OR ill need to write a fast regular expression , so just tell me how do you want it :
_some_character_search_or1|or2|or3_some_character_search_
_some_character_ can be 
1. SPACE
2. { }
3. anything else that you like :)
ex. if you want to be space it will be "2015.05.27 PROPER|REPACK|REAL " or "2015.05.27 .PROPER.|.REPACK.|.REAL. "
ex. if you want to be {} it will be "2015.05.27 {PROPER|REPACK|REAL}" or "2015.05.27 {.PROPER.|.REPACK.|.REAL.}"

**Comment by JackDandy** [comment]
@rarbg 
ok, then use {{or1|or2|or3}} that is double brace.
so 
`"2015.05.27 {{.PROPER.|.REPACK.|.REAL.}}"`

**Comment by rarbg** [comment]
@JackDandy
Ok :) As soon as v2 is ready ( 48h ) it will support OR with {{}}

**Comment by rarbg** [comment]
@JackDandy 
Can you test pubapi_v2.php ?

**Comment by JackDandy** [comment]
@rarbg 
is it correct for **search_string=2015 {{proper|repack}}** to return items where filename does NOT contain 2015 ? I expected 2015 to be ANDed with the {{}}

**Comment by rarbg** [comment]
Yes @JackDandy thats a normal behavior , exactly because of shows like forever/flash & etc

**Comment by JackDandy** [comment]
As I  thought @rarbg thanks for clearing that up :) So yeah. everything seems fine here, I just need to tweak our code a little once v2 becomes stable after adding whatever features other people are requesting.

**Comment by rarbg** [comment]
@JackDandy 
You can do category tv or movies , anyways most of the apps dont need the rest like porn

**Comment by JackDandy** [comment]
You had it perfect on v1, it saddens me when people request dumbing down of data :(

**Comment by rarbg** [comment]
But if you use the categories as integers - when we add new categories you will have to update :)
So its a win-win :)

**Comment by JackDandy** [comment]
Umm, not really. With a max. result of 100 items, merging items from a (increasing) number of qualities means that items do get pushed out of the 100 in LIFO manner... I've seen this exact symptom happen before w/usenet so that backlog started to fail to find stuff. Granularity is key here over cat item merging.

**Comment by rarbg** [comment]
1. How is the "source" ( us ) preventing you to filter for HD ex. {{720p|1080p|2160p}} ? If they choose HD send the queries with {{720p|1080p|2160p}} :)
2. Api response times are sub 50ms no-matter-what™ ( just kidding on the tm ) , so overload - no way on server side
3. You have to also keep in mind that uploader permission on our site is not enabled by default. releases are filtered and for example movies - there cant be 55 different qualities from 55 different groups
4. You cant prevent users from being stupid. You can only educated them.
5. 7*24 = 168 - even if you had the filter for HD / SD enabled again it will be out of the limit. Not to mention shows like Simpsons with 26 seasons

**Comment by JackDandy** [comment]
Given that a numeric show ID (imdb, tvdb, tvrage) is better than a string showname, then it follows that your numeric cat is also better than a string.  About, point 5... the best solution is to use a bucket pagination system, however I didn't want to put that onto you. Anyway, I have to go visit family a long distance away so these are my last words on this. Good luck whatever you decide, our code with work around and utilise whatever you make available so there is no issue, just trying to help.

All the best.
JD.

**Comment by JackDandy** [comment]
@rarbg we will keep with Api v1 as it suits our needs better than v2.

**Comment by rarbg** [comment]
@JackDandy api v1 will be deprecated in 90 days. 

----- Original Message -----

**Comment by JackDandy** [comment]
@rarbg oh no, if there is a chance that you can add the numeric cat numbering of api v1 to v2 then that would be great

**Comment by rarbg** [comment]
@JackDandy
Im busy right now but i plan to add you the functionality you want for
the category.
I hope ill finish this week api v2 

----- Original Message -----

**Comment by rarbg** [comment]
@JackDandy 
v2 now supports both strings and the old 1;2;3
Im updating the docs now and will be ready for production use today.

**Comment by JackDandy** [comment]
@rarbg Thanks :+1:

**Comment by JackDandy** [comment]
@rarbg in the response of get_token, can you supply the current token "time_remaining".

**Comment by rarbg** [comment]
@JackDandy 
Its 15 minutes AFTER the client stops making requests with the token , so the get_token will always reply with 15 minute :D

**Comment by JackDandy** [comment]
Ah, perhaps update the docs with this detail. Great, thanks again :)

**Pull request merged**
