### PR TITLE
Fix saving default show list group on add new show options page

### PR DESCRIPTION
**Pull request by adam111316**

### CODE REVIEW

**Comment by JackDandy** [comment]
perhaps convert existing saved split settings to the new setting so anime users get an instant fix and auto separation rather than having to go in there and fiddle with settings ?

**Comment by adam111316** [comment]
@JackDandy that migration is already part of old code.

**Comment by JackDandy** [comment]
Then there may be an issue with the existing migration code because it was reported that showlist/anime seperation was NOT working at all. I can only suspect that the user had perhaps moved his existing config from a different folk into sg with that option enabled or that he had tried to set the legacy option not knowing that the new groups exist. If he did set the legacy option, then there may be logic missing.

**Comment by adam111316** [comment]
The migration logic only occurs on a config upgrade from an older version. Migration does not occur when a option is saved.

**Comment by JackDandy** [comment]
yup, as suspected.

**Comment by adam111316** [comment]
Adding unnecessary migrate code bloat doesn't make sense. It's simply an option that has zero effect on anything at the moment.

**Comment by JackDandy** [comment]
bloat? really? 1/2 lines max, lol okay w/eva. cba it's anime anyway,

**Pull request merged**
