### PR TITLE
Fix init scripts to say SickGear

### PR DESCRIPTION
**Pull request by ressu**
This is a new revision of PR #15 which had some lacking scripts.

The ubuntu init script has been removed and replaced with a link to the Debian init script. All init script have been modified to work with old settings where possible so that upgrading old scripts do not produce odd results. Eventually the backwards compatibility can be dropped.

The init scripts have been moved to a separate directory to clean up the root of the development tree.

### CODE REVIEW

**Comment by MindTooth** [comment]
Status on this?

**Comment by ressu** [comment]
Rebased the branch on current develop

**Comment by ressu** [comment]
Rebased this again (No real changes). I also reorganized the commits for easier reading and separated the move from root to init-scripts as well as the ubuntu init script removal into separate commits.

**Comment by adam111316** [comment]
@JackDandy: im having a go at fixing this one up fyi

**Comment by adam111316** [comment]
Superseded by #564

**Pull request closed without merging**
